name: Main Workflow

on:
  push:
    branches: ['main', 'dpavel/CICD']
  pull_request:
    branches: ['main']

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Test and Build
        uses: ./.github/actions/test_and_build
        with:
          node-version: ${{ matrix.node-version }}

  zip:
    needs: test_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Zip
        uses: ./.github/actions/zip
